PrintV4L2RequestBuffers(): Compile fix for ancient kernels
The GitHub ubuntu image doesn't have a kernel uapi header with a `struct
v4l2_requestbuffers.flags` member.

    ../src/linux/camera.cpp: In function ‘void vacon::linux::PrintV4L2RequestBuffers(const v4l2_requestbuffers*)’:
    ../src/linux/camera.cpp:43:55: error: ‘const struct v4l2_requestbuffers’ has no member named ‘flags’
       43 |     PLOG_VERBOSE << fmt::format("flags = {}", reqbuf->flags);
          |                                                       ^~~~~